/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hip;

import javax.swing.SwingUtilities;

/**
 *
 * @author lee
 */
public class VentilatorGUI extends javax.swing.JFrame implements VentiMachineListener {
    VentiMachine vm;
    VentiUserListener vul;

    /**
     * Creates new form HelloWorldJFrame
     */
    public VentilatorGUI() {
        initComponents();
        try {
            vm = new VentiMachine(this);
            vul = vm;
            vm.start();
        }
        catch (Exception e) {
            SwingUtilities.invokeLater(()->jlP1Count.setText("Error"));
            System.err.println("SPI Error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgV1 = new javax.swing.ButtonGroup();
        bgV2 = new javax.swing.ButtonGroup();
        bgV3 = new javax.swing.ButtonGroup();
        bgRunStop = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jrbV1Open = new javax.swing.JRadioButton();
        jrbV1Close = new javax.swing.JRadioButton();
        jrbV2Open = new javax.swing.JRadioButton();
        jrbV2Close = new javax.swing.JRadioButton();
        jrbV3Open = new javax.swing.JRadioButton();
        jrbV3Close = new javax.swing.JRadioButton();
        jlP1Count = new javax.swing.JLabel();
        jlV1 = new javax.swing.JLabel();
        jlV2 = new javax.swing.JLabel();
        jlV3 = new javax.swing.JLabel();
        jlP1 = new javax.swing.JLabel();
        jlP2 = new javax.swing.JLabel();
        jrbRun = new javax.swing.JRadioButton();
        jrbStop = new javax.swing.JRadioButton();
        jlP4 = new javax.swing.JLabel();
        jlP3 = new javax.swing.JLabel();
        jlP2Count1 = new javax.swing.JLabel();
        jlP5 = new javax.swing.JLabel();
        jlP6 = new javax.swing.JLabel();
        jlP7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jlPSI4 = new javax.swing.JLabel();
        jlP2Count2 = new javax.swing.JLabel();
        jlP2Count3 = new javax.swing.JLabel();
        jlP2Count4 = new javax.swing.JLabel();
        jlP2Count5 = new javax.swing.JLabel();
        peepMinusBtn = new javax.swing.JButton();
        peepPlusBtn = new javax.swing.JButton();
        pipPlusBtn = new javax.swing.JButton();
        tvMinusBtn = new javax.swing.JButton();
        rpmPlusBtn = new javax.swing.JButton();
        pipMinusBtn = new javax.swing.JButton();
        rpmMinusBtn = new javax.swing.JButton();
        tvPlusBtn = new javax.swing.JButton();
        jlPSI6 = new javax.swing.JLabel();
        jlPSI7 = new javax.swing.JLabel();
        jlPSI8 = new javax.swing.JLabel();
        jlPSI9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bgV1.add(jrbV1Open);
        jrbV1Open.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jrbV1Open.setText("Open");
        jrbV1Open.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbV1Open.setBorderPainted(true);
        jrbV1Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbV1OpenActionPerformed(evt);
            }
        });

        bgV1.add(jrbV1Close);
        jrbV1Close.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jrbV1Close.setSelected(true);
        jrbV1Close.setText("Shut");
        jrbV1Close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbV1Close.setBorderPainted(true);
        jrbV1Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbV1CloseActionPerformed(evt);
            }
        });

        bgV2.add(jrbV2Open);
        jrbV2Open.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jrbV2Open.setText("Open");
        jrbV2Open.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbV2Open.setBorderPainted(true);
        jrbV2Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbV2OpenActionPerformed(evt);
            }
        });

        bgV2.add(jrbV2Close);
        jrbV2Close.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jrbV2Close.setSelected(true);
        jrbV2Close.setText("Shut");
        jrbV2Close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbV2Close.setBorderPainted(true);
        jrbV2Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbV2CloseActionPerformed(evt);
            }
        });

        bgV3.add(jrbV3Open);
        jrbV3Open.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jrbV3Open.setText("Open");
        jrbV3Open.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbV3Open.setBorderPainted(true);
        jrbV3Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbV3OpenActionPerformed(evt);
            }
        });

        bgV3.add(jrbV3Close);
        jrbV3Close.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jrbV3Close.setSelected(true);
        jrbV3Close.setText("Shut");
        jrbV3Close.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbV3Close.setBorderPainted(true);
        jrbV3Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbV3CloseActionPerformed(evt);
            }
        });

        jlP1Count.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP1Count.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlP1Count.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlV1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlV1.setText("V1");

        jlV2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlV2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlV2.setText("V2");

        jlV3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlV3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlV3.setText("V3");

        jlP1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlP1.setText("TP");

        jlP2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlP2.setText("Message");

        bgRunStop.add(jrbRun);
        jrbRun.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jrbRun.setText("Run");
        jrbRun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbRun.setBorderPainted(true);
        jrbRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRunActionPerformed(evt);
            }
        });

        bgRunStop.add(jrbStop);
        jrbStop.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jrbStop.setSelected(true);
        jrbStop.setText("Stop");
        jrbStop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbStop.setBorderPainted(true);
        jrbStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbStopActionPerformed(evt);
            }
        });

        jlP4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlP4.setText("LP");

        jlP3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlP3.setText("PEEP");

        jlP2Count1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP2Count1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlP2Count1.setText("5.0");
        jlP2Count1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlP5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlP5.setText("Tidal Volume");

        jlP6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlP6.setText("PIP");

        jlP7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlP7.setText("RPM");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Enable Logger");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Disable Logger");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jlPSI4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlPSI4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPSI4.setText("cc");

        jlP2Count2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP2Count2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlP2Count2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlP2Count3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP2Count3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlP2Count3.setText("12.0");
        jlP2Count3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlP2Count4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP2Count4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlP2Count4.setText("14.0");
        jlP2Count4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlP2Count5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlP2Count5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlP2Count5.setText("500.0");
        jlP2Count5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        peepMinusBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        peepMinusBtn.setText("-");
        peepMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peepMinusBtnActionPerformed(evt);
            }
        });

        peepPlusBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        peepPlusBtn.setText("+");
        peepPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peepPlusBtnActionPerformed(evt);
            }
        });

        pipPlusBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pipPlusBtn.setText("+");
        pipPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipPlusBtnActionPerformed(evt);
            }
        });

        tvMinusBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tvMinusBtn.setText("-");
        tvMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvMinusBtnActionPerformed(evt);
            }
        });

        rpmPlusBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rpmPlusBtn.setText("+");
        rpmPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpmPlusBtnActionPerformed(evt);
            }
        });

        pipMinusBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pipMinusBtn.setText("-");
        pipMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipMinusBtnActionPerformed(evt);
            }
        });

        rpmMinusBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rpmMinusBtn.setText("-");
        rpmMinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpmMinusBtnActionPerformed(evt);
            }
        });

        tvPlusBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tvPlusBtn.setText("+");
        tvPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvPlusBtnActionPerformed(evt);
            }
        });

        jlPSI6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlPSI6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPSI6.setText("<html>cm H<sub>2</sub>O");

        jlPSI7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlPSI7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPSI7.setText("<html>cm H<sub>2</sub>O");

        jlPSI8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlPSI8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPSI8.setText("<html>cm H<sub>2</sub>O");

        jlPSI9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlPSI9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPSI9.setText("<html>cm H<sub>2</sub>O");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbV1Open, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jrbV2Open, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbV3Open, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jrbRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlV2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jlV1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlV3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbV1Close, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbV3Close, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbV2Close, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbStop, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jRadioButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlP6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlP3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlP7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(56, 56, 56)
                                        .addComponent(peepMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(291, 291, 291)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rpmMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pipMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tvMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlP2Count1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlPSI6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlP2Count3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlP2Count4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlPSI7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jlP2Count5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlPSI4)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jlP5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlP2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(peepPlusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(pipPlusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(tvPlusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rpmPlusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlP4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlP1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlP1Count, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlP2Count2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPSI8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPSI9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbV1Open, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlV1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbV1Close, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbV2Open, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlV2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbV2Close, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbV3Open, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlV3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbV3Close, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbRun, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbStop, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlP2Count1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlPSI6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(peepPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlP2Count4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlPSI7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pipPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlP1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlPSI8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlP2Count2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlP4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlPSI9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlP1Count, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rpmMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlP7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlP2Count3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rpmPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tvPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlP5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tvMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlP2Count5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlPSI4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlP3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peepMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pipMinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlP6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jlP2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        vul.shutdown();
    }//GEN-LAST:event_formWindowClosing

    private void jrbRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRunActionPerformed
        vul.runAuto();
    }//GEN-LAST:event_jrbRunActionPerformed

    private void jrbStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbStopActionPerformed
        vul.stopAuto();
    }//GEN-LAST:event_jrbStopActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        vul.enableLogger();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        vul.disableLogger();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jrbV3CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbV3CloseActionPerformed
        vul.shutV3();
    }//GEN-LAST:event_jrbV3CloseActionPerformed

    private void jrbV3OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbV3OpenActionPerformed
        vul.openV3();
    }//GEN-LAST:event_jrbV3OpenActionPerformed

    private void jrbV2CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbV2CloseActionPerformed
        vul.shutV2();
    }//GEN-LAST:event_jrbV2CloseActionPerformed

    private void jrbV2OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbV2OpenActionPerformed
        vul.openV2();
    }//GEN-LAST:event_jrbV2OpenActionPerformed

    private void jrbV1CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbV1CloseActionPerformed
        vul.shutV1();
    }//GEN-LAST:event_jrbV1CloseActionPerformed

    private void jrbV1OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbV1OpenActionPerformed
        vul.openV1();
    }//GEN-LAST:event_jrbV1OpenActionPerformed

    private void peepMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peepMinusBtnActionPerformed
        vul.minusPEEP();
    }//GEN-LAST:event_peepMinusBtnActionPerformed

    private void peepPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peepPlusBtnActionPerformed
        vul.addPEEP();
    }//GEN-LAST:event_peepPlusBtnActionPerformed

    private void pipPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipPlusBtnActionPerformed
        vul.addPIP();
    }//GEN-LAST:event_pipPlusBtnActionPerformed

    private void tvMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvMinusBtnActionPerformed
        vul.minusTidalVolume();
    }//GEN-LAST:event_tvMinusBtnActionPerformed

    private void rpmPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpmPlusBtnActionPerformed
        vul.addRPM();
    }//GEN-LAST:event_rpmPlusBtnActionPerformed

    private void pipMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipMinusBtnActionPerformed
        vul.minusPIP();
    }//GEN-LAST:event_pipMinusBtnActionPerformed

    private void rpmMinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpmMinusBtnActionPerformed
        vul.minusRPM();
    }//GEN-LAST:event_rpmMinusBtnActionPerformed

    private void tvPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvPlusBtnActionPerformed
        vul.addTidalVolume();
    }//GEN-LAST:event_tvPlusBtnActionPerformed

    //Tank pressure
    @Override
    public void notifyPressures(String sTank, String sLung) {
        SwingUtilities.invokeLater(() -> {jlP2Count2.setText(sTank);
        jlP1Count.setText(sLung);        
        });
        
    }
    
    //Lung pressure
    //@Override
    //public void notifyP2(String s) {
      //  SwingUtilities.invokeLater(() -> jlP1Count.setText(s));
    //}
    
    
    /*
    
                    No longer using a third pressure sensor
    
    @Override
    public void notifyP3(String s) {
        SwingUtilities.invokeLater(() -> jlP3Count.setText(s));
    }
    
    @Override
    public void notifyP3(float f) {
        notifyP3(String.format("%.2f", f));
    }
    */ 
    
    //Sends message to message box which is wrapped in a scroll pane: uses apend function
    @Override
    public void notifyMessageBox(String s) {
        SwingUtilities.invokeLater(() -> jTextArea1.append(s));
    }
    
    //Checks if PEEP has reached max, adds 0.5 cm H20 if it hasn't, converts PEEP to a string, and displays it on GUI
    @Override
    public void notifyPEEP(String s) {
        SwingUtilities.invokeLater(() -> jlP2Count1.setText(s));
    }
    
    //Checks if PIP has reached max, adds 1.0 cm H20 if it hasn't, converts PIP to a string, and displays it on GUI
    @Override
    public void notifyPIP(String s) {
        SwingUtilities.invokeLater(() -> jlP2Count4.setText(s));
    }
    
    //Checks if RPM has reached max, adds 1.0/min if it hasn't, converts RPM to a string, and displays it on GUI
    @Override
    public void notifyRPM(String s) {
        SwingUtilities.invokeLater(() -> jlP2Count3.setText(s));   
    }
    
    //Checks if TV has reached max, adds 25 cc if it hasn't, converts TV to a string, and displays it on GUI
    @Override
    public void notifyTidalVolume(String s) {
        SwingUtilities.invokeLater(() -> jlP2Count5.setText(s));    
    }
    
    
    /* Shouldn't need to change, just DELETE
    
    
    //Checks if PEEP has reached min, subtracts 0.5 cm H20 if it hasn't, converts PEEP to a string, and displays it on GUI
    @Override
    public void minusPEEP() {
       jlP2Count1.setText(vm.minusPEEP());
    }
    
    //Checks if PIP has reached min, subtracts 1.0 cm H20 if it hasn't, converts PIP to a string, and displays it on GUI
    @Override
    public void minusPIP() {
        jlP2Count4.setText(vm.minusPIP());
    }
    
    //Checks if RPM has reached min, subtracts 1.0/min if it hasn't, converts RPM to a string, and displays it on GUI
    @Override
    public void minusRPM() {
        jlP2Count3.setText(vm.minusRPM());
    }
    
    //Checks if TV has reached min, subtracts 25 cc if it hasn't, converts TV to a string, and displays it on GUI
    @Override
    public void minusTidalVolume() {
        jlP2Count5.setText(vm.minusTidalVolume());
    }
    */
    
    @Override
    public void notifyValvesEnabled(String s) {
        boolean bo = Boolean.parseBoolean(s);
        SwingUtilities.invokeLater(() -> {
                    jrbV1Open.setEnabled(bo);
                    jrbV1Close.setEnabled(bo);
                    jrbV2Open.setEnabled(bo);
                    jrbV2Close.setEnabled(bo);
                    jrbV3Open.setEnabled(bo);
                    jrbV3Close.setEnabled(bo);
                });
    }
    
    @Override
    public void notifyV1State(String s) {
        boolean bo = Boolean.parseBoolean(s);
        SwingUtilities.invokeLater(() -> {
                    if(bo) {
                        jrbV1Open.setSelected(true);
                    }
                    else {
                        jrbV1Close.setSelected(true);
                    }
                });
    }
    
    @Override
    public void notifyV2State(String s) {
        boolean bo = Boolean.parseBoolean(s);
        SwingUtilities.invokeLater(() -> {
                    if(bo) {
                        jrbV2Open.setSelected(true);
                    }
                    else {
                        jrbV2Close.setSelected(true);
                    }
                });
    }
    
    @Override
    public void notifyV3State(String s) {
        boolean bo = Boolean.parseBoolean(s);
        SwingUtilities.invokeLater(() -> {
                    if(bo) {
                        jrbV3Open.setSelected(true);
                    }
                    else {
                        jrbV3Close.setSelected(true);
                    }
                });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentilatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentilatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentilatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentilatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentilatorGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgRunStop;
    private javax.swing.ButtonGroup bgV1;
    private javax.swing.ButtonGroup bgV2;
    private javax.swing.ButtonGroup bgV3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jlP1;
    private javax.swing.JLabel jlP1Count;
    private javax.swing.JLabel jlP2;
    private javax.swing.JLabel jlP2Count1;
    private javax.swing.JLabel jlP2Count2;
    private javax.swing.JLabel jlP2Count3;
    private javax.swing.JLabel jlP2Count4;
    private javax.swing.JLabel jlP2Count5;
    private javax.swing.JLabel jlP3;
    private javax.swing.JLabel jlP4;
    private javax.swing.JLabel jlP5;
    private javax.swing.JLabel jlP6;
    private javax.swing.JLabel jlP7;
    private javax.swing.JLabel jlPSI4;
    private javax.swing.JLabel jlPSI6;
    private javax.swing.JLabel jlPSI7;
    private javax.swing.JLabel jlPSI8;
    private javax.swing.JLabel jlPSI9;
    private javax.swing.JLabel jlV1;
    private javax.swing.JLabel jlV2;
    private javax.swing.JLabel jlV3;
    public javax.swing.JRadioButton jrbRun;
    private javax.swing.JRadioButton jrbStop;
    private javax.swing.JRadioButton jrbV1Close;
    private javax.swing.JRadioButton jrbV1Open;
    private javax.swing.JRadioButton jrbV2Close;
    private javax.swing.JRadioButton jrbV2Open;
    private javax.swing.JRadioButton jrbV3Close;
    private javax.swing.JRadioButton jrbV3Open;
    private javax.swing.JButton peepMinusBtn;
    private javax.swing.JButton peepPlusBtn;
    private javax.swing.JButton pipMinusBtn;
    private javax.swing.JButton pipPlusBtn;
    private javax.swing.JButton rpmMinusBtn;
    private javax.swing.JButton rpmPlusBtn;
    private javax.swing.JButton tvMinusBtn;
    private javax.swing.JButton tvPlusBtn;
    // End of variables declaration//GEN-END:variables

}
